apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ks-ipam
rules:
  - apiGroups:
      - network.kubesphere.io
    resources:
      - ippools
      - ipamhandles
      - ipamconfigs
      - ipamblocks
      - blockaffinities
    verbs: ["list", "watch", "get","update", "patch", "create", "delete"]
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
