
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: ippools.network.kubesphere.io
spec:
  group: network.kubesphere.io
  names:
    categories:
    - network
    kind: IPPool
    plural: ippools
  scope: Cluster
  validation:
    openAPIV3Schema:
      description: IPPool contains information about an IPPool resource.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: Standard object's metadata.
          type: object
        spec:
          description: Specification of the IPPool.
          properties:
            blockSize:
              description: The block size to use for IP address assignments from this
                pool. Defaults to 26 for IPv4 and 112 for IPv6.
              type: integer
            cidr:
              description: The pool CIDR.
              type: string
            dhcp:
              type: boolean
            disabled:
              description: When disabled is true, Calico IPAM will not assign addresses
                from this pool.
              type: boolean
            dns:
              description: DNS contains values interesting for DNS resolvers
              properties:
                domain:
                  type: string
                nameservers:
                  items:
                    type: string
                  type: array
                options:
                  items:
                    type: string
                  type: array
                search:
                  items:
                    type: string
                  type: array
              type: object
            gateway:
              type: string
            nodeSelector:
              description: Allows IPPool to allocate for a specific node by label
                selector.
              type: string
            rangeEnd:
              type: string
            rangeStart:
              description: Add By Kubesphere The following fields will be used for
                Macvtap
              type: string
            routes:
              items:
                properties:
                  dst:
                    type: string
                  gateway:
                    type: string
                type: object
              type: array
            vlanConfig:
              properties:
                master:
                  type: string
                vlanId:
                  format: int32
                  type: integer
              required:
              - master
              - vlanId
              type: object
          required:
          - cidr
          type: object
        status:
          properties:
            allocations:
              type: integer
            reserved:
              type: integer
            total:
              type: integer
            unallocated:
              description: Unallocated should equal to (Total - Reserved - Allocations)
              type: integer
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
