
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: ipamconfigs.network.kubesphere.io
spec:
  group: network.kubesphere.io
  names:
    categories:
    - network
    kind: IPAMConfig
    plural: ipamconfigs
  scope: Cluster
  validation:
    openAPIV3Schema:
      description: IPAMConfig contains information about a block for IP address assignment.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: Standard object's metadata.
          type: object
        spec:
          description: Specification of the IPAMConfig.
          properties:
            autoAllocateBlocks:
              type: boolean
            maxBlocksPerHost:
              description: MaxBlocksPerHost, if non-zero, is the max number of blocks
                that can be affine to each host.
              type: integer
            strictAffinity:
              type: boolean
          required:
          - autoAllocateBlocks
          - strictAffinity
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
