
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: ipamhandles.network.kubesphere.io
spec:
  group: network.kubesphere.io
  names:
    categories:
    - network
    kind: IPAMHandle
    plural: ipamhandles
  scope: Cluster
  validation:
    openAPIV3Schema:
      description: IPAMHandle contains information about an IPAMHandle resource.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: Standard object's metadata.
          type: object
        spec:
          description: Specification of the IPAMHandle.
          properties:
            block:
              additionalProperties:
                type: integer
              type: object
            handleID:
              type: string
          required:
          - block
          - handleID
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
